ci wip

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -7,32 +7,45 @@ jobs:
     name: iomidipp_ci (${{ matrix.os }})
     runs-on: ${{ matrix.os }}
     env:
-      source-dir: ./sources
-      build-dir: ./build
-      install-prefix: ./install
+      # relative to repo root
+      rel-build-dir: build # where targets will be built
+      rel-install-prefix: install # where built targets and testdata is installed to
+      rel-source-dir: sources # where the root CMakeLists.txt resides
     strategy:
       fail-fast: false
       matrix:
         os: ['ubuntu-latest', 'macos-latest']
     steps:
       - uses: actions/checkout@v2
-      - name: create build and install dir
-        shell: bash -l {0}
-        run: mkdir ${{build-dir}} && mkdir ${{install-prefix}}
       - name: Get latest CMake and ninja
         uses: lukka/get-cmake@latest
       - name: configure, build, install, test
         shell: bash -l {0}
         run: |
+          echo "$(pwd)"
+          exit 1
+          INSTALL_PREFIX="$(pwd)/${REL_INSTALL_PREFIX}"
+          BUILD_DIR="$(pwd)/${REL_BUILD_DIR}"
+          SOURCE_DIR="$(pwd)/${REL_SOURCE_DIR}"
+          echo "install prefix: ${INSTALL_PREFIX}"
+          echo "build dir: ${BUILD_DIR}"
+          echo "source dir: ${SOURCE_DIR}"
+          cd ${BUILD_DIR}
           cmake -DIOMIDIPP_CREATE_TEST_TARGET=BOOL:ON -DCMAKE_INSTALL_PREFIX="${INSTALL_PREFIX}" ${SOURCE_DIR}
           cmake --build
           cmake --build . --target install
           cd ${INSTALL_PREFIX}/bin
           ./iomidipp_tests.exe
-        working-directory: ${{build-dir}}
+          err_code=$?
+          if [ ${err_code} -ne 0 ]; then
+              ret_code=${err_code}
+              echo "tests failed with ${ret_code}"
+          fi
+          exit ${ret_code}
         env:
-          INSTALL_PREFIX: ${{ install-prefix }}
-          SOURCE_DIR: ${{ source-dir }}
+          REL_BUILD_DIR: ${{ rel-build-dir }}
+          REL_INSTALL_PREFIX: ${{ rel-install-prefix }}
+          REL_SOURCE_DIR: ${{ rel-source-dir }}
 #  iomidipp_ci_windows:
 #    name: iomidipp_ci (${{ matrix.os }})
 #    runs-on: ${{ matrix.os }}
