ci wip

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -33,6 +33,8 @@ jobs:
           echo "build dir: ${BUILD_DIR}"
           echo "source dir: ${SOURCE_DIR}"
           mkdir ${REL_INSTALL_PREFIX}
+          mkdir ${REL_INSTALL_PREFIX}/bin
+          mkdir ${REL_INSTALL_PREFIX}/lib
           mkdir ${REL_BUILD_DIR}
           echo "ls: $(ls)"
           echo "LD_LIBRARY_PATH before ${LD_LIBRARY_PATH}"
@@ -57,7 +59,52 @@ jobs:
 #  iomidipp_ci_windows:
 #    name: iomidipp_ci (${{ matrix.os }})
 #    runs-on: ${{ matrix.os }}
+#    env:
+#      # relative to repo root
+#      rel-build-dir: build # where targets will be built
+#      rel-install-prefix: install # where built targets and testdata is installed to
+#      rel-source-dir: sources # where the root CMakeLists.txt resides
 #    strategy:
 #      fail-fast: false
 #      matrix:
 #        os: ['windows-latest']
+#    steps:
+#      - uses: actions/checkout@v2
+#        with:
+#        submodules: 'true'
+#      - name: Get latest CMake and ninja
+#        uses: lukka/get-cmake@latest
+#      - name: configure, build, install, test
+#        shell: bash -l {0}
+#        run: |
+#          INSTALL_PREFIX="$(pwd)/${REL_INSTALL_PREFIX}"
+#          BUILD_DIR="$(pwd)/${REL_BUILD_DIR}"
+#          SOURCE_DIR="$(pwd)/${REL_SOURCE_DIR}"
+#          echo "install prefix: ${INSTALL_PREFIX}"
+#          echo "build dir: ${BUILD_DIR}"
+#          echo "source dir: ${SOURCE_DIR}"
+#          mkdir ${REL_INSTALL_PREFIX}
+#          mkdir ${REL_INSTALL_PREFIX}/bin
+#          mkdir ${REL_INSTALL_PREFIX}/lib
+#          mkdir ${REL_BUILD_DIR}
+#          echo "ls: $(ls)"
+#          echo "LD_LIBRARY_PATH before ${LD_LIBRARY_PATH}"
+#          LD_LIBRARY_PATH=${LD_LIBRARY_PATH};${INSTALL_PREFIX}/lib
+#          echo "LD_LIBRARY_PATH after ${LD_LIBRARY_PATH}"
+#          cd ${BUILD_DIR}
+#          cmake -DIOMIDIPP_CREATE_TEST_TARGET=BOOL:ON -DCMAKE_INSTALL_PREFIX="${INSTALL_PREFIX}" -DCMAKE_BUILD_TYPE=Release ${SOURCE_DIR}
+#          cmake --build .
+#          cmake --build . --target install
+#          cd ${INSTALL_PREFIX}/bin
+#          ./iomidipp_tests
+#          err_code=$?
+#          if [ ${err_code} -ne 0 ]; then
+#              ret_code=${err_code}
+#              echo "tests failed with ${ret_code}"
+#          fi
+#          exit ${ret_code}
+#        env:
+#          REL_BUILD_DIR: ${{ env.rel-build-dir }}
+#          REL_INSTALL_PREFIX: ${{ env.rel-install-prefix }}
+#          REL_SOURCE_DIR: ${{ env.rel-source-dir }}
+#
